export const GET_SEARCH_RESULT_FROM_SERVER: string = "GET_SEARCH_RESULT_FROM_SERVER";
export const GET_SEARCH_RESULT_FOR_TABLE: string = "GET_SEARCH_RESULT_FOR_TABLE";
export const EDIT_ENTRY_RESULT: string = "EDIT_ENTRY_RESULT";
