export const GET_SEARCH_RESULT_FROM_SERVER = "GET_SEARCH_RESULT_FROM_SERVER";
export const GET_SEARCH_RESULT_FOR_TABLE = "GET_SEARCH_RESULT_FOR_TABLE";
export const EDIT_ENTRY_RESULT = "EDIT_ENTRY_RESULT";
